name: Django CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  Test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check code quality
      run: |
        flake8

  Deploy:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} 
    name: Deploy
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Connect and Execute Commands
      uses: appleboy/ssh-action@master
      with:
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        host: ${{secrets.HOST}}
        port: ${{secrets.PORT}}
        script: |
          cd ${{secrets.PROJECT_PATH}}
          source ../.venv/bin/activate
          git pull
          python manage.py migrate
          python manage.py collectstatic --noinput
          systemctl restart apache2
